import type { Character, Group } from './types';

export const PJSK_GROUPS: Group[] = [
    {id: 'ln', characters: []},
    {id: 'mmj', characters: []},
    {id: 'vbs', characters: []},
    {id: 'wxs', characters: []},
    {id: '25n', characters: []},
];

export const PJSK_ORIGINAL_CHARACTERS: Character[] = [
    {id: 'ichika', spriteImageUrl: '/img/pjsk/ichika.png', group: 'unassigned'},
    {id: 'saki', spriteImageUrl: '/img/pjsk/saki.png', group: 'unassigned'},
    {id: 'honami', spriteImageUrl: '/img/pjsk/honami.png', group: 'unassigned'},
    {id: 'shiho', spriteImageUrl: '/img/pjsk/shiho.png', group: 'unassigned'},
    {id: 'minori', spriteImageUrl: '/img/pjsk/minori.png', group: 'unassigned'},
    {id: 'haruka', spriteImageUrl: '/img/pjsk/haruka.png', group: 'unassigned'},
    {id: 'airi', spriteImageUrl: '/img/pjsk/airi.png', group: 'unassigned'},
    {id: 'shizuku', spriteImageUrl: '/img/pjsk/shizuku.png', group: 'unassigned'},
    {id: 'kohane', spriteImageUrl: '/img/pjsk/kohane.png', group: 'unassigned'},
    {id: 'an', spriteImageUrl: '/img/pjsk/an.png', group: 'unassigned'},
    {id: 'akito', spriteImageUrl: '/img/pjsk/akito.png', group: 'unassigned'},
    {id: 'toya', spriteImageUrl: '/img/pjsk/toya.png', group: 'unassigned'},
    {id: 'tsukasa', spriteImageUrl: '/img/pjsk/tsukasa.png', group: 'unassigned'},
    {id: 'rui', spriteImageUrl: '/img/pjsk/rui.png', group: 'unassigned'},
    {id: 'emu', spriteImageUrl: '/img/pjsk/emu.png', group: 'unassigned'},
    {id: 'nene', spriteImageUrl: '/img/pjsk/nene.png', group: 'unassigned'},
    {id: 'kanade', spriteImageUrl: '/img/pjsk/kanade.png', group: 'unassigned'},
    {id: 'mafuyu', spriteImageUrl: '/img/pjsk/mafuyu.png', group: 'unassigned'},
    {id: 'mizuki', spriteImageUrl: '/img/pjsk/mizuki.png', group: 'unassigned'},
    {id: 'ena', spriteImageUrl: '/img/pjsk/ena.png', group: 'unassigned'},
];

export const BANDORI_GROUPS: Group[] = [
    {id: 'ppp', characters: []},
    {id: 'ag', characters: []},
    {id: 'pp', characters: []},
    {id: 'rose', characters: []},
    {id: 'hhw', characters: []},
    {id: 'morf', characters: []},
    {id: 'ras', characters: []},
    {id: 'mygo', characters: []},
    {id: 'am', characters: []},
];

export const BANDORI_CHARACTERS: Character[] = [
    {id: 'kasumi', spriteImageUrl: '/img/bandori/kasumi.webp', group: 'unassigned'},
    {id: 'tae', spriteImageUrl: '/img/bandori/tae.webp', group: 'unassigned'},
    {id: 'rimi', spriteImageUrl: '/img/bandori/rimi.webp', group: 'unassigned'},
    {id: 'saya', spriteImageUrl: '/img/bandori/saya.webp', group: 'unassigned'},
    {id: 'arisa', spriteImageUrl: '/img/bandori/arisa.webp', group: 'unassigned'},
    {id: 'ran', spriteImageUrl: '/img/bandori/ran.webp', group: 'unassigned'},
    {id: 'moca', spriteImageUrl: '/img/bandori/moca.webp', group: 'unassigned'},
    {id: 'himari', spriteImageUrl: '/img/bandori/himari.webp', group: 'unassigned'},
    {id: 'tomoe', spriteImageUrl: '/img/bandori/tomoe.webp', group: 'unassigned'},
    {id: 'tsugumi', spriteImageUrl: '/img/bandori/tsugumi.webp', group: 'unassigned'},
    {id: 'aya', spriteImageUrl: '/img/bandori/aya.webp', group: 'unassigned'},
    {id: 'hina', spriteImageUrl: '/img/bandori/hina.webp', group: 'unassigned'},
    {id: 'chisato', spriteImageUrl: '/img/bandori/chisato.webp', group: 'unassigned'},
    {id: 'maya', spriteImageUrl: '/img/bandori/maya.webp', group: 'unassigned'},
    {id: 'eve', spriteImageUrl: '/img/bandori/eve.webp', group: 'unassigned'},
    {id: 'yukina', spriteImageUrl: '/img/bandori/yukina.webp', group: 'unassigned'},
    {id: 'sayo', spriteImageUrl: '/img/bandori/sayo.webp', group: 'unassigned'},
    {id: 'lisa', spriteImageUrl: '/img/bandori/lisa.webp', group: 'unassigned'},
    {id: 'ako', spriteImageUrl: '/img/bandori/ako.webp', group: 'unassigned'},
    {id: 'rinko', spriteImageUrl: '/img/bandori/rinko.webp', group: 'unassigned'},
    {id: 'kokoro', spriteImageUrl: '/img/bandori/kokoro.webp', group: 'unassigned'},
    {id: 'kaoru', spriteImageUrl: '/img/bandori/kaoru.webp', group: 'unassigned'},
    {id: 'hagumi', spriteImageUrl: '/img/bandori/hagumi.webp', group: 'unassigned'},
    {id: 'kanon', spriteImageUrl: '/img/bandori/kanon.webp', group: 'unassigned'},
    {id: 'misaki', spriteImageUrl: '/img/bandori/misaki.webp', group: 'unassigned'},
    {id: 'mashiro', spriteImageUrl: '/img/bandori/mashiro.webp', group: 'unassigned'},
    {id: 'touko', spriteImageUrl: '/img/bandori/touko.webp', group: 'unassigned'},
    {id: 'nanami', spriteImageUrl: '/img/bandori/nanami.webp', group: 'unassigned'},
    {id: 'tsukushi', spriteImageUrl: '/img/bandori/tsukushi.webp', group: 'unassigned'},
    {id: 'rui', spriteImageUrl: '/img/bandori/rui.webp', group: 'unassigned'},
    {id: 'layer', spriteImageUrl: '/img/bandori/layer.webp', group: 'unassigned'},
    {id: 'lock', spriteImageUrl: '/img/bandori/lock.webp', group: 'unassigned'},
    {id: 'masking', spriteImageUrl: '/img/bandori/masking.webp', group: 'unassigned'},
    {id: 'pareo', spriteImageUrl: '/img/bandori/pareo.webp', group: 'unassigned'},
    {id: 'chuchu', spriteImageUrl: '/img/bandori/chuchu.webp', group: 'unassigned'},
    {id: 'tomori', spriteImageUrl: '/img/bandori/tomori.webp', group: 'unassigned'},
    {id: 'anon', spriteImageUrl: '/img/bandori/anon.webp', group: 'unassigned'},
    {id: 'rana', spriteImageUrl: '/img/bandori/rana.webp', group: 'unassigned'},
    {id: 'soyo', spriteImageUrl: '/img/bandori/soyo.webp', group: 'unassigned'},
    {id: 'taki', spriteImageUrl: '/img/bandori/taki.webp', group: 'unassigned'},
    {id: 'uika', spriteImageUrl: '/img/bandori/uika.webp', group: 'unassigned'},
    {id: 'mutsumi', spriteImageUrl: '/img/bandori/mutsumi.webp', group: 'unassigned'},
    {id: 'umiri', spriteImageUrl: '/img/bandori/umiri.webp', group: 'unassigned'},
    {id: 'nyamu', spriteImageUrl: '/img/bandori/nyamu.webp', group: 'unassigned'},
    {id: 'sakiko', spriteImageUrl: '/img/bandori/sakiko.webp', group: 'unassigned'},
];
